version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-api-with-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-motpcbx21udm"
s3_prefix = "my-api-with-sam"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
